// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class ScoreLeaderBoard
{
        public const string achievement_eat_250_corns = "CgkIxLn4os8TEAIQBw"; // <GPGSID>
        public const string achievement_eat_30_corns = "CgkIxLn4os8TEAIQBA"; // <GPGSID>
        public const string achievement_eat_80_corns = "CgkIxLn4os8TEAIQBQ"; // <GPGSID>
        public const string leaderboard_score = "CgkIxLn4os8TEAIQCQ"; // <GPGSID>
        public const string achievement_eat_at_least_100_corns_in_3_consecutive_games = "CgkIxLn4os8TEAIQCg"; // <GPGSID>
        public const string achievement_eat_200_corns = "CgkIxLn4os8TEAIQBg"; // <GPGSID>
        public const string achievement_eat_10_corns = "CgkIxLn4os8TEAIQAw"; // <GPGSID>

}

